/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/ufl-panels.glb --keepnames -o ./src/components/Panels.tsx 
*/
import {} from "tweakpane";
import * as THREE from "three";
import { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { useControls } from "leva";



type GLTFResult = GLTF & {
  nodes: {
    Ufl_Panel_Center: THREE.Mesh;
    Ufl_Panel_Left: THREE.Mesh;
    Ufl_Panel_Right: THREE.Mesh;
  };
  materials: {
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
  };
};

export function Panels(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/models/ufl-panels.glb",
  ) as unknown as GLTFResult;

  const groupRef = useRef<THREE.Group>(null);

  const rectlightref = useRef(null);

  const {intensity,power} = useControls({
    intensity:{
      value:15,
      min:0,
      max:50,
      step:.1
    },
    power:{
      value:500,
      min:0,
      max:500,
      step:.1
    },
  })

  // useHelper(rectlightref,RectAreaLightHelper,'yellow');

  return (
    <group {...props} ref={groupRef} dispose={null}>
      <rectAreaLight 
        ref={rectlightref}
        position={[0, .85 ,0]}
        width={1}
        height={2.5}
        color={'#0e9cff'}
        intensity={intensity}
        power={power}

        rotation={[0,Math.PI,0]}
      />
      <mesh
        name="Ufl_Panel_Center"
        geometry={nodes.Ufl_Panel_Center.geometry}
        position={[0, -0.38, 0]}
      >
        <PanelMaterial />
      </mesh>
      <mesh
        name="Ufl_Panel_Left"
        geometry={nodes.Ufl_Panel_Left.geometry}
        position={[-0.4, -0.38, 0]}
      >
        <PanelMaterial />
      </mesh>
      <mesh
        name="Ufl_Panel_Right"
        geometry={nodes.Ufl_Panel_Right.geometry}
        position={[0.4, -0.38, 0]}
      >
        <PanelMaterial />
      </mesh>
    </group>
  );
}

function PanelMaterial() {
  const { color, emissive, emissiveIntensity } = useControls(
    "Panels",
    {
      color: {
        value: "#0e9cff",
        // value: "#ffffff",
      },
      emissive: {
        value: "#69d0ff",
        // value: "#ffffff",
      },
      emissiveIntensity: {
        value: 2,
        min: 0,
        max: 50,
        step: 0.1,
      },
    },
    {
      collapsed: true,
    },
  );

  return (
    <meshStandardMaterial
      color={color}
      emissive={emissive}
      emissiveIntensity={emissiveIntensity}
    />
  );
}

useGLTF.preload("/models/ufl-panels.glb");
