/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/ufl-panels.glb --keepnames -o ./src/components/Panels.tsx 
*/
import {} from "tweakpane";
import * as THREE from "three";
import { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { useControls } from "leva";

type GLTFResult = GLTF & {
  nodes: {
    Ufl_Panel_Center: THREE.Mesh;
    Ufl_Panel_Left: THREE.Mesh;
    Ufl_Panel_Right: THREE.Mesh;
  };
  materials: {
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
  };
};

export function Panels(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/ufl-panels.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Ufl_Panel_Center"
        geometry={nodes.Ufl_Panel_Center.geometry}
        position={[0, -0.38, 0]}
      >
        <PanelMaterial />
      </mesh>
      <mesh
        name="Ufl_Panel_Left"
        geometry={nodes.Ufl_Panel_Left.geometry}
        position={[-0.4, -0.38, 0]}
      >
        <PanelMaterial />
      </mesh>
      <mesh
        name="Ufl_Panel_Right"
        geometry={nodes.Ufl_Panel_Right.geometry}
        position={[0.4, -0.38, 0]}
      >
        <PanelMaterial />
      </mesh>
    </group>
  );
}

function PanelMaterial() {
  const { color, emissive, emissiveIntensity } = useControls(
    "Panels",
    {
      color: {
        value: "#f5f5f5",
      },
      emissive: {
        value: "#a0e6ff",
      },
      emissiveIntensity: {
        value: 1,
        min: 0,
        max: 5,
        step: 0.1,
      },
    },
    {
      collapsed: true,
    },
  );

  return (
    <meshStandardMaterial
      color={color}
      emissive={emissive}
      emissiveIntensity={emissiveIntensity}
    />
  );
}

useGLTF.preload("/models/ufl-panels.glb");
