/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/ufl.glb --keepnames -o ./src/components/Ufl.tsx 
*/

import * as THREE from "three";
import React, { useEffect, type JSX } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { type GLTF, SkeletonUtils } from "three-stdlib";

type ActionName = "warm-up";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.SkinnedMesh;
    Shirt: THREE.SkinnedMesh;
    Shoes: THREE.SkinnedMesh;
    Shorts: THREE.SkinnedMesh;
    Socks: THREE.SkinnedMesh;
    ball: THREE.Mesh;
    stand: THREE.Mesh;
    mixamorig5Hips: THREE.Bone;
  };
  materials: {
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Ufl(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/models/ufl.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["warm-up"]?.play();

    return () => {
      actions["warm-up"]?.reset();
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Ufl_Subject"
          position={[0, -0.377, 0.366]}
          rotation={[0, 0.256, 0]}
          scale={0.771}
        >
          <group name="Player" position={[0, -0.018, 0.003]}>
            <primitive object={nodes.mixamorig5Hips} />
            <skinnedMesh
              name="Body"
              geometry={nodes.Body.geometry}
              skeleton={nodes.Body.skeleton}
            >
              <UflMaterial roughness={0.6} />
            </skinnedMesh>
            <skinnedMesh
              name="Shirt"
              geometry={nodes.Shirt.geometry}
              skeleton={nodes.Shirt.skeleton}
            >
              <UflMaterial roughness={0.6} />
            </skinnedMesh>
            <skinnedMesh
              name="Shoes"
              geometry={nodes.Shoes.geometry}
              skeleton={nodes.Shoes.skeleton}
            >
              <UflMaterial roughness={0.6} />
            </skinnedMesh>
            <skinnedMesh
              name="Shorts"
              geometry={nodes.Shorts.geometry}
              skeleton={nodes.Shorts.skeleton}
            >
              <UflMaterial roughness={0.6} />
            </skinnedMesh>
            <skinnedMesh
              name="Socks"
              geometry={nodes.Socks.geometry}
              skeleton={nodes.Socks.skeleton}
            >
              <UflMaterial roughness={0.6} />
            </skinnedMesh>
            <UflMaterial roughness={0.6} />
          </group>
        </group>
        <mesh
          name="ball"
          geometry={nodes.ball.geometry}
          position={[-0.031, -0.289, 0.729]}
        >
          <UflMaterial roughness={0.} />
        </mesh>
        <mesh
          name="stand"
          geometry={nodes.stand.geometry}
          position={[1.647, -0.38, 0]}
          scale={[1, 1, 0.6]}
        >
          <UflMaterial roughness={1} />
        </mesh>
      </group>
    </group>
  );
}

const UflMaterial = ({ roughness = 1 }: { roughness: number }) => {
  return (
    <meshStandardMaterial
      color={0x000000}
      emissive={0x000000}
      metalness={1}
      roughness={roughness}
    />
  );
};

useGLTF.preload("/models/ufl.glb");
